goal:
  description: >
    The agent acts as a Twitter user. Every 20 minutes it searches for tweets about "AI agents",
    and responds to no more than 10 of them per hour with friendly and intelligent messages.
    Additionally, the agent should consider context sent by the only authorized user via DM
    (if ever needed), and store this in best practices (but LLMProcessor logic remains unchanged).
    It can also check likes and replies to its own tweets,
    and then (optionally) update best practices based on this data.
  success_criteria:
    - "Do not exceed the limit of 10 replies per hour"
    - "Search for tweets every 20 minutes (tweet_search)"
    - "Each reply call must not violate guardrails"
    - "Update best practices when needed using the LLMProcessor mechanism"
