goal:
  description: >
    Агент выступает в роли пользователя Твиттера. Каждые 20 минут он ищет твиты по теме "AI agents",
    и отвечает не более чем на 10 из них в час дружелюбными и умными сообщениями. 
    Кроме того, агент должен учитывать контекст, который присылает ему единственный разрешённый пользователь в DM
    (если когда-нибудь понадобится), и хранить это в best practices (но логика LLMProcessor не меняется).
    При этом он может проверять лайки и реплаи своих собственных твитов, 
    а потом (опционально) обновлять best practices на основании этих данных.
  success_criteria:
    - "Не превышать лимит 10 ответов в час"
    - "Каждые 20 минут делать поиск твитов (tweet_search)"
    - "Каждый вызов reply не должен нарушать guardrails"
    - "Обновлять best practices при необходимости за счёт механизма LLMProcessor"
